########################
# Spring boot properties
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
########################
spring:
  profiles:
    active: verbose
  output:
    ansi:
      enabled: ALWAYS
  ##################################
  flyway:
    enabled: true
    clean-on-validation-error: true
    baseline-on-migrate: true
  ##################################
  datasource:
    url: jdbc:postgresql://localhost:26257/spring_boot?sslmode=disable
    driver-class-name: org.postgresql.Driver
    username: root
    password:
    hikari:
      maximum-pool-size: 50
      minimum-idle: 25
    batch-size: 50
  ##################################
  jackson:
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail_on_unknown_properties: false
      fail_on_ignored_properties: false
    default-property-inclusion: non_null
    locale: en_US
##################################
server:
  port: 8090
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always
  jetty:
    threads:
      max: 250
#############################
logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr([%logger{39}]){cyan} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
