########################
# Spring boot properties
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
########################

spring:
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:postgresql://localhost:26257/roach_spring?sslmode=disable
    driver-class-name: org.postgresql.Driver
    username: root
    password:
    hikari:
      connection-test-query: SELECT 1
      auto-commit: true

  flyway:
    enabled: true
    clean-on-validation-error: true
    baseline-on-migrate: false
    locations: classpath:db

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.CockroachDB201Dialect
        connection:
          provider_disables_autocommit: false
