roach:
  datasources:
    alpha:
      url: jdbc:postgresql://192.168.1.99:26300/roach_spring_boot_alpha?sslmode=disable
      driver-class-name: org.postgresql.Driver
      username: root
      password:
    bravo:
      url: jdbc:postgresql://192.168.1.99:26300/roach_spring_boot_bravo?sslmode=disable
      driver-class-name: org.postgresql.Driver
      username: root
      password:
    caesar:
      url: jdbc:postgresql://192.168.1.99:26300/roach_spring_boot_caesar?sslmode=disable
      driver-class-name: org.postgresql.Driver
      username: root
      password:
