spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_boot
    driver-class-name: org.postgresql.Driver
    username: root
    password:
