spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.CockroachDB201Dialect
  datasource:
    url: jdbc:postgresql://localhost:26257/spring_boot?sslmode=disable
    driver-class-name: org.postgresql.Driver
    username: root
    password:
