########################
# Spring boot properties
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
########################
spring:
  profiles:
    active: verbose
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:postgresql://localhost:26257/spring_boot?sslmode=disable
    driver-class-name: org.postgresql.Driver
    username: root
    password:
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 15000
      validation-timeout: 5000
      maximum-pool-size: 25
      minimum-idle: 25
      register-mbeans: false

  flyway:
    connect-retries: 10
    enabled: true
    locations: classpath:db/migration
    clean-on-validation-error: true
    baseline-on-migrate: true
    clean-disabled: false

  jpa:
    open-in-view: false
    properties:
        hibernate:
          dialect: io.roach.spring.tree.config.CockroachDB221Dialect
