########################
# Spring boot properties
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
########################
spring:
  profiles:
    active: verbose
  main:
    allow-circular-references: true
  output:
    ansi:
      enabled: ALWAYS
  flyway:
    enabled: true
    clean-on-validation-error: true
    baseline-on-migrate: true
    clean-disabled: false
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:26257/spring_boot?sslmode=disable
    driver-class-name: org.postgresql.Driver
    username: root
    password:
    hikari:
# Should be cluster_total_vcpus * 4 / num_pool_instances
      maximum-pool-size: 50
# Should be same as maxPoolSize for fixed-sized pool
      minimum-idle: 25
      max-lifetime: 1800000
#############################
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: conditions,env,health,metrics,prometheus,info
#############################
server:
  port: 8090
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always
    path: /error
#############################
logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr([%logger{39}]){cyan} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"