########################
# Spring boot properties
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
########################

spring:
  profiles:
    active: jpa
  output:
    ansi:
      enabled: ALWAYS
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    open-in-view: false
server:
  port: 8090
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always
    path: /error
info:
  build:
    artifact: roach-spring-annotations
roach:
  datasource:
    url: jdbc:postgresql://localhost:26257/roach_spring?sslmode=disable
    driver-class-name: org.postgresql.Driver
    username: root
    password:
    configuration:
      connection-test-query: SELECT 1
      connection-timeout: 15000
      validation-timeout: 5000
      max-lifetime: 30000
      maximum-pool-size: 25
